### ISSUE TITLE
Multiple apps on vps?

### ISSUE THREAD

**Issue by cvandermeer** [intercity/chef-repo#162]
After successfully putting my first app online using this repo. I wondered is it possible to put multiple apps on my vps using chef-repo?

**Comment by michiels** [comment]
Yes! That's one of the most important features of this repository.

Just add another application to the `active_applications` key in your json configuration file and it works the same as the other app you already have!

**Comment by cvandermeer** [comment]
Does this mean i keep the application that is already on there in the json file. Or do i replace it with the new app information?

**Comment by jvanbaarsen** [comment]
Yes You keep all the apps you want on the server in the JSON file. Chef will look at the JSON file and determine which commands it needs to run, and which are already ran.

**Comment by michiels** [comment]
You keep it in there. So you will have two applications with a different name in the `active_applications` key in the json file.

**Comment by berkes** [comment]
I'm trying to improve the documentation and this seems like a good opportunity to make some improvements. @cvandermeer, some questions:

* Were you aware of the [wiki](https://github.com/intercity/chef-repo/wiki/)? (If not, we've got an opportunity to announce it better)
* Did you find enough basic information about this repos capabilities and features, between the Wiki and the README? (obviously we haven't communicated clear enough that/how you can run multiple apps)
* Any other feedback on the documentation? Too much? Too little? Too much work in progress? etc?

**Comment by cvandermeer** [comment]
* I wasn't aware of the wiki yet.
* Through the issue's i found an example filled in json configuration file which was very helpfull. Some Capistrano issues but those were easily googled(Things like secret base key). Maybe also a sample file for postgresql, i also found this in the issues.
* I think the readme is clear and clean, i now that i know of the wiki it is a good expansionof the readme.
