### ISSUE TITLE
Set min_instances for passenger based installations

### ISSUE THREAD

**Issue by jvanbaarsen** [intercity/chef-repo#169]
set `passenger_min_instances` to 1 so passenger makes sure that one process is always present.

**Comment by oiuzikov** [comment]
@jvanbaarsen according to the passenger's docs, the default already 1:

https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#PassengerMinInstances

**Comment by jvanbaarsen** [comment]
"This option may only occur once, in the http configuration block. The default value is 0."

**Comment by oiuzikov** [comment]
Just to clarify:

![selection_089](https://cloud.githubusercontent.com/assets/462925/6036589/037350d8-ac50-11e4-9b43-8eeba65e86f5.png)

**Comment by jvanbaarsen** [comment]
Hm Now I'm confused :p

**Comment by oiuzikov** [comment]
What are you confused with? Is this issue still valid?

**Comment by jvanbaarsen** [comment]
I have to check.

**Comment by michiels** [comment]
Was this a bug report? Maybe the passenger got killed because of out of memory or a re-deploy?

**Comment by jvanbaarsen** [comment]
No it was something mentioned by one of the people I talked about for IC. But seems like the default is 1, I've misread it I guess. So for now this issue is invalid. People can change this once we start supporting custom NGINX configs.
