### ISSUE TITLE
Error preparing the server

### ISSUE THREAD

**Issue by arturictus** [intercity/chef-repo#199]
bundle exec knife solo prepare < user >@< ip >
Bootstrapping Chef...
Enter the password for < user >@< ip >:
ERROR: SyntaxError: (eval):1: syntax error, unexpected ':', expecting end-of-input
...Solo::Bootstraps::bash:warning:setlocale:LC_ALL:cannotchange...

**Comment by arturictus** [comment]
Fixed running:
```
 dpkg-reconfigure locales
```
http://ubuntuforums.org/showthread.php?t=1346581

**Comment by michiels** [comment]
Hey @arturictus. Thanks for the report and the solution :) Just to be sure: was this a DigitalOcean droplet, or something else? We've seen lots of people having this problem with DO because locales aren't generated in their base Ubuntu images.

Thanks!

**Comment by arturictus** [comment]
Hi @michiels,
I'm working with OVH.

**Comment by michiels** [comment]
Hey @arturictus,

Ok. Thanks for letting us know. We know now that people from OVH might also need to reconfigure their locales. We'll be sure to mention it in the documentation and support :)

Michiel
