### ISSUE TITLE
Asking Multiple times root's password on 'cook'

### ISSUE THREAD

**Issue by arturictus** [intercity/chef-repo#200]
Hi,
When cooking the server it ask me multiple times the root's password.
Checking online I found is caused by Rsync. Is that a natural behavior?, can it be automated?.
Thanks.
I paste here the cook sequence:
```
bundle exec knife solo cook root@<ip>
Running Chef on <ip>...
Checking Chef version...
Enter the password for root@<ip>:
Installing Librarian cookbooks...
Uploading the kitchen...
root@<ip>'s password:
root@<ip>'s password:
root@<ip>'s password:
root@<ip>'s password:
root@<ip>'s password:
root@<ip>'s password:
root@<ip>'s password:
Generating solo config...
root@<ip>'s password:
Running Chef...
```

**Comment by cvandermeer** [comment]
Because you didn't set up ssh public key.

**Comment by michiels** [comment]
Hi @arturictus 

As @cvandermeer mentioned: you could solve this by adding the SSH key of your workstation (located in ~/.ssh/id_rsa.pub) to the `authorized_keys` file on your server located at `/root/.ssh/authorized_key`

If you add your personal key to the root account, it will not ask you a password anymore.

Does this help?
Michiel

**Comment by arturictus** [comment]
Yeah! :+1:
Thanks, that make sense :smile: .

**Comment by michiels** [comment]
Great! :) I'll close this issue.
