### ISSUE TITLE
Chef 12 server support?

### ISSUE THREAD

**Issue by lauer** [intercity/chef-repo#207]
Hi, I had problems configuring a chef 12 client, until I figured that its because intercity chef-repo is defining chef as version 11 in Gemfile. 

After changing that to version `gem "chef", "~> 12.5.1"` and a `bundle update` and `knife rehash`, it worked fine. 

So I don't know if this is deliberate, but isn't the chef 12 standard most places?

**Comment by michiels** [comment]
Hey!

Thanks for the heads-up! There is no deliberate reason for using only Chef 11. I'm currently working on the update to add Chef 12 as default. I will commit it to master after doing a test run.

Michiel

**Comment by michiels** [comment]
@lauer I just merged in https://github.com/intercity/chef-repo/pull/208 into master, so will be available in the next release, or right now if you're using our master branch :)
